# Generated by Django 6.0.5 on 2026-06-14 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('bairro', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.CharField(max_length=8)),
                ('numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nascimento', models.DateField()),
                ('pessoas', models.IntegerField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='adotantes/')),
                ('tipo_residencia', models.CharField(choices=[('C', 'Casa'), ('A', 'Apartamento'), ('CH', 'Chácara'), ('O', 'Outro')], max_length=2)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20)),
                ('deficiencias', models.ManyToManyField(blank=True, related_name='adotantes', to='core.deficiencia')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adotantes', to='adotantes.endereco')),
            ],
            options={
                'verbose_name': 'Adotante',
                'verbose_name_plural': 'Adotantes',
            },
        ),
    ]
