# Generated by Django 6.0.5 on 2026-06-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='numero',
            field=models.CharField(default=2, max_length=10),
            preserve_default=False,
        ),
    ]
