# Generated by Django 6.0.5 on 2026-06-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adotantes', '0002_endereco_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adotante',
            name='tipo_residencia',
            field=models.CharField(choices=[('C', 'Casa'), ('A', 'Apartamento'), ('CH', 'Chácara'), ('O', 'Outro')], max_length=2),
        ),
    ]
