# Generated by Django 6.0.5 on 2026-06-14 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='racas', to='animais.especie')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], max_length=1)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=1)),
                ('status', models.CharField(choices=[('Disponivel', 'Disponível'), ('Tratamento', 'Em Tratamento'), ('Adotado', 'Adotado'), ('Obito', 'Óbito')], default='Disponivel', max_length=20)),
                ('data_resgate', models.DateField()),
                ('castrado', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('historia', models.TextField()),
                ('foto', models.ImageField(upload_to='fotos_animais/')),
                ('deficiencias', models.ManyToManyField(blank=True, to='core.deficiencia')),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='animais.especie')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animais', to='animais.raca')),
            ],
        ),
    ]
