# Generated by Django 6.0.5 on 2026-05-31 20:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.TextField(blank=True, null=True)),
                ('funcao', models.CharField(max_length=100)),
                ('data_entrada', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('AFASTADO', 'Afastado')], default='ATIVO', max_length=20)),
                ('nivel_acesso', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('FUNCIONARIO', 'Funcionário'), ('VOLUNTARIO', 'Voluntário'), ('VETERINARIO', 'Veterinário')], default='FUNCIONARIO', max_length=20)),
                ('login', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('senha_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
